import type { GarmentDefinition, SleevePart } from './types';

/**
 * Demo catalogue. All four garments are original placeholder artwork generated by
 * scripts/generate-garments.mjs (CC0-1.0). Replace `body` with a transparent garment cutout and
 * adjust `anchors`/`fit` to use real products; `sleeves` is optional.
 */

const BODY = { width: 600, height: 720 };
const DEMO_LICENSE = {
  name: 'CC0-1.0',
  author: 'virtual-fitting-mirror project (original demo artwork)',
  notes: 'Placeholder garment drawn for this prototype; not a real product.',
};

/** Shared anchor geometry of the generated body images (see scripts/generate-garments.mjs). */
const DEMO_ANCHORS = {
  leftShoulder: { x: 425 / BODY.width, y: 120 / BODY.height },
  rightShoulder: { x: 175 / BODY.width, y: 120 / BODY.height },
  neck: { x: 300 / BODY.width, y: 95 / BODY.height },
  hem: { x: 300 / BODY.width, y: 680 / BODY.height },
};

const deg = (d: number) => (d * Math.PI) / 180;

function demoSleeves(id: string): { left: SleevePart; right: SleevePart } {
  const common = {
    width: 200,
    height: 170,
    pivot: { x: 100 / 200, y: 22 / 170 },
    axisAngle: Math.PI / 2,
    restOutward: deg(12),
    minOutward: deg(4),
    maxOutward: deg(150),
  };
  return {
    left: { ...common, src: `garments/${id}/sleeve-left.svg` },
    right: { ...common, src: `garments/${id}/sleeve-right.svg` },
  };
}

function demoGarment(id: string, name: string, description: string, fit?: Partial<GarmentDefinition['fit']>) {
  return {
    id,
    name,
    description,
    preview: `garments/${id}/preview.svg`,
    body: { src: `garments/${id}/body.svg`, ...BODY },
    sleeves: demoSleeves(id),
    anchors: DEMO_ANCHORS,
    fit: { widthScale: 1.18, lengthScale: 0.97, verticalOffset: -0.12, ...fit },
    supportedViews: ['front'],
    license: DEMO_LICENSE,
    demo: true,
  } satisfies GarmentDefinition;
}

export const GARMENTS: readonly GarmentDefinition[] = [
  demoGarment('coral-crew-tee', 'Coral crew tee', 'Solid crew-neck T-shirt'),
  demoGarment('breton-stripe-tee', 'Breton stripe', 'Striped boat-neck top'),
  demoGarment('chambray-button-shirt', 'Chambray shirt', 'Short-sleeve button-up with collar'),
  demoGarment('forest-v-neck', 'Forest V-neck', 'V-neck T-shirt'),
];

export const DEFAULT_GARMENT_ID = GARMENTS[0]?.id ?? '';

export function findGarment(id: string | null | undefined): GarmentDefinition {
  const first = GARMENTS[0];
  if (!first) throw new Error('Garment catalogue is empty');
  return GARMENTS.find((g) => g.id === id) ?? first;
}
